version: '1'

services:
  frontend:
    env_file:
      - .env
    command: npm run start
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped
  backend:
    env_file:
      - .env
    command: npm run serverProd
    build:
      context: .
    ports:
      - "5000:5000"